#!/usr/bin/ruby
require 'stringio'
require 'logger'
require 'pp'

load './syntax_node.rb'
load './if_then_else_node.rb'
load './select_node.rb'
load './archaic_do_loop.rb'
load './fortran_parser.rb'

@logger = Logger.new(STDERR)
@logger.level = Logger::INFO

if ARGV.size != 1
  STDERR.puts "Usage: #$0 INFILE"
  exit 1
end

tree = parse_file(ARGV[0])

def print_tree(tree)
  puts "digraph AST {"
  tree.dot_nodes.each { |node| puts node }
  tree.dot_edges.each { |node| puts node }
  puts "}"
end

# puts tree.to_s
# print_tree tree
subtree = tree[[[:module, "MG_STENCIL_COMPS_MOD"], [:subroutine, "MG_STENCIL_2D5PT"]]]
# puts subtree
# pp subtree
print_tree subtree
