#!/usr/bin/ruby
require 'stringio'
require 'logger'
require 'pp'

load './fortran_parser.rb'

if ARGV.size != 1
  STDERR.puts "Usage: #$0 INFILE"
  exit 1
end

parser = FortranParser.new
tree = parser.parse_file(ARGV[0])

# puts tree.to_s
# print_tree tree
subtree = tree[[[:module, "MG_STENCIL_COMPS_MOD"], [:subroutine, "MG_STENCIL_2D5PT"]]]
# puts subtree
# pp subtree

puts subtree.to_cpp
